/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * NewJFrame.java
 *
 * Created on 08.Nis.2010, 16:18:51
 */


import java.awt.Color;
import java.awt.Dimension;
import java.lang.Math;
import java.awt.Graphics;
import java.io.*;
import java.util.*;
import java.io.File;
import java.io.FileNotFoundException;
import java.util.Scanner;
import java.io.FileOutputStream;
import java.io.BufferedWriter;

/**
 *
 * @author sss
 */






public class NewJFrame extends javax.swing.JFrame {

    double birinci;
    double ikinci;
    double sonuc;
    int topla=0;
    int cikar=0;
    int carp=0;
    int bol=0;
    int sin=0;
    int cos=0;
    int ln=0;
    int tiklandimi=0;
    int islemyaptim=0;
    int kontrol=-1;
    dosya oku=new dosya();
    dosyayayaz yaz2=new dosyayayaz();
    String newline = System.getProperty("line.separator");













    /** Creates new form NewJFrame */
    public NewJFrame() {
        initComponents();

    }



    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jButton_YEDI = new javax.swing.JButton();
        jButton_SEKIZ = new javax.swing.JButton();
        jButton_DOKUZ = new javax.swing.JButton();
        jButton_ALTI = new javax.swing.JButton();
        jButton_BES = new javax.swing.JButton();
        jButton_DORT = new javax.swing.JButton();
        jButton_UC = new javax.swing.JButton();
        jButton_IKI = new javax.swing.JButton();
        jButton_BIR = new javax.swing.JButton();
        jButton_CLEAR = new javax.swing.JButton();
        jButton_NOKTA = new javax.swing.JButton();
        jButton_SIFIR = new javax.swing.JButton();
        jButton_CARP = new javax.swing.JButton();
        jButton_CIKAR = new javax.swing.JButton();
        jButton_TOPLA = new javax.swing.JButton();
        jButton_BOLU = new javax.swing.JButton();
        jButton_LN = new javax.swing.JButton();
        jButton_COS = new javax.swing.JButton();
        jButton_SIN = new javax.swing.JButton();
        GOSTER = new javax.swing.JTextField();
        jButton_ESITTIR = new javax.swing.JButton();
        jPanel1 = new JPanel12();
        GOSTER2 = new javax.swing.JTextField();
        jButton_OKU = new javax.swing.JButton();



        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Hesap Makinasý");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setForeground(new java.awt.Color(236, 233, 216));
        setResizable(false);

        jButton_YEDI.setFont(new java.awt.Font("Trebuchet MS", 1, 18));
        jButton_YEDI.setText("7");
        jButton_YEDI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_YEDIActionPerformed(evt);
            }
        });

        jButton_SEKIZ.setFont(new java.awt.Font("Trebuchet MS", 1, 18));
        jButton_SEKIZ.setText("8");
        jButton_SEKIZ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_SEKIZActionPerformed(evt);
            }
        });

        jButton_DOKUZ.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jButton_DOKUZ.setText("9");
        jButton_DOKUZ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_DOKUZActionPerformed(evt);
            }
        });

        jButton_ALTI.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jButton_ALTI.setText("6");
        jButton_ALTI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ALTIActionPerformed(evt);
            }
        });

        jButton_BES.setFont(new java.awt.Font("Trebuchet MS", 1, 18));
        jButton_BES.setText("5");
        jButton_BES.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_BESActionPerformed(evt);
            }
        });

        jButton_DORT.setFont(new java.awt.Font("Trebuchet MS", 1, 18));
        jButton_DORT.setText("4");
        jButton_DORT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_DORTActionPerformed(evt);
            }
        });

        jButton_UC.setFont(new java.awt.Font("Trebuchet MS", 1, 18));
        jButton_UC.setText("3");
        jButton_UC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_UCActionPerformed(evt);
            }
        });

        jButton_IKI.setFont(new java.awt.Font("Trebuchet MS", 1, 18));
        jButton_IKI.setText("2");
        jButton_IKI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_IKIActionPerformed(evt);
            }
        });

        jButton_BIR.setFont(new java.awt.Font("Trebuchet MS", 1, 18));
        jButton_BIR.setText("1");
        jButton_BIR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_BIRActionPerformed(evt);
            }
        });

        jButton_CLEAR.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jButton_CLEAR.setText("C");
        jButton_CLEAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_CLEARActionPerformed(evt);
            }
        });

        jButton_NOKTA.setFont(new java.awt.Font("Trebuchet MS", 1, 18));
        jButton_NOKTA.setForeground(new java.awt.Color(51, 51, 51));
        jButton_NOKTA.setText(".");
        jButton_NOKTA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_NOKTAActionPerformed(evt);
            }
        });

        jButton_SIFIR.setFont(new java.awt.Font("Trebuchet MS", 1, 18));
        jButton_SIFIR.setText("0");
        jButton_SIFIR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_SIFIRActionPerformed(evt);
            }
        });

        jButton_CARP.setFont(new java.awt.Font("Trebuchet MS", 1, 18));
        jButton_CARP.setText("x");
        jButton_CARP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_CARPActionPerformed(evt);
            }
        });

        jButton_CIKAR.setFont(new java.awt.Font("Trebuchet MS", 1, 18));
        jButton_CIKAR.setText("-");
        jButton_CIKAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_CIKARActionPerformed(evt);
            }
        });

        jButton_TOPLA.setFont(new java.awt.Font("Trebuchet MS", 1, 18));
        jButton_TOPLA.setText("+");
        jButton_TOPLA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_TOPLAActionPerformed(evt);
            }
        });

        jButton_BOLU.setFont(new java.awt.Font("Trebuchet MS", 1, 18));
        jButton_BOLU.setText("/");
        jButton_BOLU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_BOLUActionPerformed(evt);
            }
        });

        jButton_LN.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton_LN.setText("ln");
        jButton_LN.setToolTipText("Finds the Natural Logarithm value of the number in degrees");
        jButton_LN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_LNActionPerformed(evt);
            }
        });

        jButton_COS.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton_COS.setText("cos");
        jButton_COS.setToolTipText("Finds the Cos value of the number in degrees");
        jButton_COS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_COSActionPerformed(evt);
            }
        });

        jButton_SIN.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton_SIN.setText("sin");
        jButton_SIN.setToolTipText("Finds the Sin value of the number in degrees");
        jButton_SIN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_SINActionPerformed(evt);
            }
        });

        GOSTER.setEditable(false);
        GOSTER.setFont(new java.awt.Font("Trebuchet MS", 1, 30)); // NOI18N
        GOSTER.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        GOSTER.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 204, 255), 1, true));
        GOSTER.setOpaque(false);

        jButton_ESITTIR.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jButton_ESITTIR.setText("=");
        jButton_ESITTIR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ESITTIRActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 285, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 289, Short.MAX_VALUE)
        );

        jButton_OKU.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton_OKU.setText("oku");
        jButton_OKU.setToolTipText("Finds the Sin value of the number in degrees");
        jButton_OKU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_OKUActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jButton_ESITTIR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton_COS, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
                            .addComponent(jButton_LN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton_SIN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton_SIFIR, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton_NOKTA, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton_CLEAR, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton_BIR, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton_IKI, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton_UC, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jButton_DORT, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jButton_BES, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jButton_ALTI, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jButton_YEDI, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jButton_SEKIZ, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jButton_DOKUZ, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton_BOLU, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton_CARP, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jButton_CIKAR, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButton_TOPLA, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(13, 13, 13))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(GOSTER2, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(8, 8, 8)
                                .addComponent(jButton_OKU))
                            .addComponent(GOSTER))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGap(59, 59, 59))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(127, 127, 127)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(GOSTER2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_OKU))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(GOSTER, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton_TOPLA, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton_CIKAR, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton_CARP, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton_BOLU, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButton_YEDI, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton_SEKIZ, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton_DOKUZ, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButton_DORT, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton_BES, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton_ALTI, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButton_BIR, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton_IKI, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton_UC, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButton_SIFIR, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton_NOKTA, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton_CLEAR, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton_SIN, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton_COS, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton_LN, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton_ESITTIR, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(70, 70, 70))
        );

        pack();
    }// </editor-fold>

    private void jButton_UCActionPerformed(java.awt.event.ActionEvent evt) {
        if(tiklandimi==1){
            GOSTER.setText("");
            tiklandimi=0;
        }
        GOSTER.setText(GOSTER.getText()+"3");
}

    private void jButton_IKIActionPerformed(java.awt.event.ActionEvent evt) {
        if(tiklandimi==1){
            GOSTER.setText("");
            tiklandimi=0;
        }
        GOSTER.setText(GOSTER.getText()+"2");
}

    private void jButton_DOKUZActionPerformed(java.awt.event.ActionEvent evt) {
        if(tiklandimi==1){
            GOSTER.setText("");
            tiklandimi=0;
        }
        GOSTER.setText(GOSTER.getText()+"9");
}

    private void jButton_ALTIActionPerformed(java.awt.event.ActionEvent evt) {
        if(tiklandimi==1){
            GOSTER.setText("");
            tiklandimi=0;
        }
        GOSTER.setText(GOSTER.getText()+"6");
}

    private void jButton_BESActionPerformed(java.awt.event.ActionEvent evt) {
        if(tiklandimi==1){
            GOSTER.setText("");
            tiklandimi=0;
        }
        GOSTER.setText(GOSTER.getText()+"5");


}

    private void jButton_DORTActionPerformed(java.awt.event.ActionEvent evt) {
        if(tiklandimi==1){
            GOSTER.setText("");
            tiklandimi=0;
        }
        GOSTER.setText(GOSTER.getText()+"4");
}

    private void jButton_BIRActionPerformed(java.awt.event.ActionEvent evt) {
        if(tiklandimi==1){
            GOSTER.setText("");
            tiklandimi=0;
        }
        GOSTER.setText(GOSTER.getText()+"1");
}

    private void jButton_YEDIActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        if(tiklandimi==1){
            GOSTER.setText("");
            tiklandimi=0;
        }
        GOSTER.setText(GOSTER.getText()+"7");
}

    private void jButton_SINActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        birinci=(Double.parseDouble(GOSTER.getText()));

        sonuc=Math.sin(Math.toRadians(birinci));
        GOSTER.setText(String.valueOf(sonuc));
        yaz2.strLine="Birinci Sayi = "+String.valueOf(birinci)+" "+"Ýslem Sonucu = "+String.valueOf(sonuc)+" "+"Ýslem =  Sinüs\r\n";
        yaz2.hadiyaz();
        sonuc=0;
        tiklandimi=1;
}

    private void jButton_SEKIZActionPerformed(java.awt.event.ActionEvent evt) {
        if(tiklandimi==1){
            GOSTER.setText("");
            tiklandimi=0;
        }
        GOSTER.setText(GOSTER.getText()+"8");
}

    private void jButton_NOKTAActionPerformed(java.awt.event.ActionEvent evt) {

        kontrol=GOSTER.getText().indexOf('.');
        if(kontrol>-1 && topla==0&&cikar==0&&carp==0&&bol==0&&tiklandimi==0 ){}

        else {
            if(tiklandimi==1){
                GOSTER.setText("");
                tiklandimi=0;
            }
            GOSTER.setText(GOSTER.getText()+".");}
}

    private void jButton_CLEARActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        GOSTER.setText("");
        topla=0;
        birinci=0;
        ikinci=0;
        sonuc=0;

        cikar=0;
        carp=0;
        bol=0;
        sin=0;
        cos=0;
        ln=0;
        tiklandimi=0;
}

    private void jButton_CARPActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        if(topla>0){
            ikinci=Double.parseDouble(GOSTER.getText());
            sonuc=birinci+ikinci;
            GOSTER.setText(String.valueOf(sonuc));

            tiklandimi=1;
            ikinci=0;
            topla=0;
            cikar=0;
            carp=0;
            bol=0;
        }
        if(cikar>0){
            ikinci=Double.parseDouble(GOSTER.getText());
            sonuc=birinci-ikinci;
            GOSTER.setText(String.valueOf(sonuc));

            tiklandimi=1;
            ikinci=0;
            topla=0;
            cikar=0;
            carp=0;
            bol=0;
        }
        if(carp>0){
            ikinci=Double.parseDouble(GOSTER.getText());
            sonuc=birinci*ikinci;
            GOSTER.setText(String.valueOf(sonuc));

            tiklandimi=1;
            ikinci=0;
            topla=0;
            cikar=0;
            carp=0;
            bol=0;
        }
        if(bol>0){
            ikinci=Double.parseDouble(GOSTER.getText());
            sonuc=birinci/ikinci;
            GOSTER.setText(String.valueOf(sonuc));

            tiklandimi=1;
            ikinci=0;
            topla=0;
            cikar=0;
            carp=0;
            bol=0;
        }



        birinci=(Double.parseDouble(GOSTER.getText()));
        if(tiklandimi<1){
            GOSTER.setText("");}
        topla=0;

        cikar=0;
        carp=1;
        bol=0;
        sin=0;
        cos=0;
        ln=0;
}

    private void jButton_SIFIRActionPerformed(java.awt.event.ActionEvent evt) {
        if(tiklandimi==1){
            GOSTER.setText("");
            tiklandimi=0;
        }
        GOSTER.setText(GOSTER.getText()+"0");
}

    private void jButton_TOPLAActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        if(topla>0){
            ikinci=Double.parseDouble(GOSTER.getText());
            sonuc=birinci+ikinci;
            GOSTER.setText(String.valueOf(sonuc));

            tiklandimi=1;
            ikinci=0;
            topla=0;
            cikar=0;
            carp=0;
            bol=0;
            islemyaptim=1;

        }
        if(cikar>0){
            ikinci=Double.parseDouble(GOSTER.getText());
            sonuc=birinci-ikinci;
            GOSTER.setText(String.valueOf(sonuc));

            tiklandimi=1;
            ikinci=0;
            topla=0;
            cikar=0;
            carp=0;
            bol=0;
        }
        if(carp>0){
            ikinci=Double.parseDouble(GOSTER.getText());
            sonuc=birinci*ikinci;
            GOSTER.setText(String.valueOf(sonuc));

            tiklandimi=1;
            ikinci=0;
            topla=0;
            cikar=0;
            carp=0;
            bol=0;
        }
        if(bol>0){
            ikinci=Double.parseDouble(GOSTER.getText());
            sonuc=birinci/ikinci;
            GOSTER.setText(String.valueOf(sonuc));

            tiklandimi=1;
            ikinci=0;
            topla=0;
            cikar=0;
            carp=0;
            bol=0;

        }






        birinci=(Double.parseDouble(GOSTER.getText()));

        if(tiklandimi<1){
            GOSTER.setText("");}


        topla=1;

        cikar=0;
        carp=0;
        bol=0;
        sin=0;
        cos=0;
        ln=0;

    }

    private void jButton_CIKARActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        if(topla>0){
            ikinci=Double.parseDouble(GOSTER.getText());
            sonuc=birinci+ikinci;
            GOSTER.setText(String.valueOf(sonuc));

            tiklandimi=1;
            ikinci=0;
            topla=0;
            cikar=0;
            carp=0;
            bol=0;
        }
        if(cikar>0){
            ikinci=Double.parseDouble(GOSTER.getText());
            sonuc=birinci-ikinci;
            GOSTER.setText(String.valueOf(sonuc));

            tiklandimi=1;
            ikinci=0;
            topla=0;
            cikar=0;
            carp=0;
            bol=0;
        }
        if(carp>0){
            ikinci=Double.parseDouble(GOSTER.getText());
            sonuc=birinci*ikinci;
            GOSTER.setText(String.valueOf(sonuc));

            tiklandimi=1;
            ikinci=0;
            topla=0;
            cikar=0;
            carp=0;
            bol=0;
        }
        if(bol>0){
            ikinci=Double.parseDouble(GOSTER.getText());
            sonuc=birinci/ikinci;
            GOSTER.setText(String.valueOf(sonuc));

            tiklandimi=1;
            ikinci=0;
            topla=0;
            cikar=0;
            carp=0;
            bol=0;
        }



        birinci=(Double.parseDouble(GOSTER.getText()));
        if(tiklandimi<1){
            GOSTER.setText("");}
        topla=0;

        cikar=1;
        carp=0;
        bol=0;
        sin=0;
        cos=0;
        ln=0;
}

    private void jButton_LNActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        birinci=(Double.parseDouble(GOSTER.getText()));

        sonuc=Math.log(birinci);
        yaz2.strLine="Birinci Sayi = "+String.valueOf(birinci)+" "+"Ýslem Sonucu = "+String.valueOf(sonuc)+" "+"Ýslem =  Doðal Logaritma\r\n";
        yaz2.hadiyaz();
        GOSTER.setText(String.valueOf(sonuc));
        sonuc=0;
        tiklandimi=1;
}

    private void jButton_BOLUActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        if(topla>0){
            ikinci=Double.parseDouble(GOSTER.getText());
            sonuc=birinci+ikinci;
            GOSTER.setText(String.valueOf(sonuc));

            tiklandimi=1;
            ikinci=0;
            topla=0;
            cikar=0;
            carp=0;
            bol=0;
        }
        if(cikar>0){
            ikinci=Double.parseDouble(GOSTER.getText());
            sonuc=birinci-ikinci;
            GOSTER.setText(String.valueOf(sonuc));

            tiklandimi=1;
            ikinci=0;
            topla=0;
            cikar=0;
            carp=0;
            bol=0;
        }
        if(carp>0){
            ikinci=Double.parseDouble(GOSTER.getText());
            sonuc=birinci*ikinci;
            GOSTER.setText(String.valueOf(sonuc));

            tiklandimi=1;
            ikinci=0;
            topla=0;
            cikar=0;
            carp=0;
            bol=0;
        }
        if(bol>0){
            ikinci=Double.parseDouble(GOSTER.getText());
            sonuc=birinci/ikinci;
            GOSTER.setText(String.valueOf(sonuc));

            tiklandimi=1;
            ikinci=0;
            topla=0;
            cikar=0;
            carp=0;
            bol=0;
        }



        birinci=(Double.parseDouble(GOSTER.getText()));
        if(tiklandimi<1){
            GOSTER.setText("");}
        topla=0;

        cikar=0;
        carp=0;
        bol=1;
        sin=0;
        cos=0;
        ln=0;
}

    private void jButton_ESITTIRActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        ikinci=(Double.parseDouble(GOSTER.getText()));
        tiklandimi=1;
        if(topla>0){
            sonuc=birinci+ikinci;
            GOSTER.setText(String.valueOf(sonuc));
            yaz2.strLine="Birinci Sayi = "+String.valueOf(birinci)+" "+"Ýkinci Sayý = "+String.valueOf(ikinci)+" "+"Ýslem Sonucu = "+String.valueOf(sonuc)+" "+"Ýslem =  Toplama\r\n";
            yaz2.hadiyaz();
            birinci=0;
            ikinci=0;
            topla=0;
            tiklandimi=1;


        }
        if(cikar>0){
            sonuc=birinci-ikinci;
            GOSTER.setText(String.valueOf(sonuc));
            yaz2.strLine="Birinci Sayi = "+String.valueOf(birinci)+" "+"Ýkinci Sayý = "+String.valueOf(ikinci)+" "+"Ýslem Sonucu = "+String.valueOf(sonuc)+" "+"Ýslem =  Çikarma\r\n";
            yaz2.hadiyaz();
            birinci=0;
            ikinci=0;
            cikar=0;
            tiklandimi=1;

        }

        if(carp>0){
            sonuc=birinci*ikinci;
            GOSTER.setText(String.valueOf(sonuc));
            yaz2.strLine="Birinci Sayi = "+String.valueOf(birinci)+" "+"Ýkinci Sayý = "+String.valueOf(ikinci)+" "+"Ýslem Sonucu = "+String.valueOf(sonuc)+" "+"Ýslem =  Çarpma\r\n";
            yaz2.hadiyaz();
            birinci=0;
            ikinci=0;
            carp=0;
            tiklandimi=1;

        }

        if(bol>0){
            sonuc=birinci/ikinci;
            GOSTER.setText(String.valueOf(sonuc));
            yaz2.strLine="Birinci Sayi = "+String.valueOf(birinci)+" "+"Ýkinci Sayý = "+String.valueOf(ikinci)+" "+"Ýslem Sonucu = "+String.valueOf(sonuc)+" "+"Ýslem =  Bölme\r\n";
            yaz2.hadiyaz();
            birinci=0;
            ikinci=0;
            bol=0;
            tiklandimi=1;

        }
    }

    private void jButton_COSActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        birinci=(Double.parseDouble(GOSTER.getText()));

        sonuc=Math.cos(Math.toRadians(birinci));
        GOSTER.setText(String.valueOf(sonuc));
        yaz2.strLine="Birinci Sayi = "+String.valueOf(birinci)+" "+"Ýslem Sonucu = "+String.valueOf(sonuc)+" "+"Ýslem =  Cosinus\r\n";
        yaz2.hadiyaz();
        sonuc=0;
        tiklandimi=1;

}

    private void jButton_OKUActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:

                oku.oku();
                GOSTER2.setText(oku.sss);
}

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {



        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);




            }
        });

    }

    // Variables declaration - do not modify
    private javax.swing.JTextField GOSTER;
    private javax.swing.JTextField GOSTER2;
    private javax.swing.JButton jButton_ALTI;
    private javax.swing.JButton jButton_BES;
    private javax.swing.JButton jButton_BIR;
    private javax.swing.JButton jButton_BOLU;
    private javax.swing.JButton jButton_CARP;
    private javax.swing.JButton jButton_CIKAR;
    private javax.swing.JButton jButton_CLEAR;
    private javax.swing.JButton jButton_COS;
    private javax.swing.JButton jButton_DOKUZ;
    private javax.swing.JButton jButton_DORT;
    private javax.swing.JButton jButton_ESITTIR;
    private javax.swing.JButton jButton_IKI;
    private javax.swing.JButton jButton_LN;
    private javax.swing.JButton jButton_NOKTA;
    private javax.swing.JButton jButton_OKU;
    private javax.swing.JButton jButton_SEKIZ;
    private javax.swing.JButton jButton_SIFIR;
    private javax.swing.JButton jButton_SIN;
    private javax.swing.JButton jButton_TOPLA;
    private javax.swing.JButton jButton_UC;
    private javax.swing.JButton jButton_YEDI;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration

}

class JPanel12 extends javax.swing.JPanel{
    public void paint(Graphics t){
    t.setColor(Color.red);
    t.drawOval(15, 15, 200, 200);
    t.setColor(Color.blue);
    t.drawString("Hesap Makinasýna Hoþ Geldiniz", 25, 125);
    t.fillRect(15, 250, 200, 50);
    t.setColor(Color.WHITE);
    t.drawString("Salih ERÝKCÝ", 80, 270);

    }


}
class dosya {
 	public String sss="";
	public  void oku() {
		try {
			//okuma
			Scanner sc=new Scanner(new File("dosya.txt"));
			while(sc.hasNext()){
			sss=sss+sc.nextLine();
			}

		} catch (FileNotFoundException e) {

			sss=e.getMessage();
		}

	}

}

class dosya2 {
 	public String sss2="";
	public  void oku() {
		try {
			//okuma
			Scanner sc2=new Scanner(new File("islem.txt"));
			while(sc2.hasNext()){
				if(sss2.length()==0){
					sss2=sc2.nextLine();}
					else{

			sss2=sss2+"\r\n"+sc2.nextLine();}

			}

		} catch (FileNotFoundException e) {
			// TODO Auto-generated catch block
			sss2="";
		}

	}

}


 class dosyayayaz {
 	public String strLine;
     public  void hadiyaz() {
     	dosya2 onceoku=new dosya2();
     	onceoku.oku();



          try {
               File file = new File("islem.txt") ; // yeni dosya olustur.
               FileWriter fwriter = new FileWriter(file) ;
               BufferedWriter bw = new BufferedWriter(fwriter) ;



  bw.write(onceoku.sss2+"\r\n");

  bw.write(strLine);
               bw.close() ;
          } catch(IOException ioexc) {}
     }
}







